<map id="django.views.debug.ExceptionReporter.get_traceback_frames" name="django.views.debug.ExceptionReporter.get_traceback_frames">
<area shape="rect" id="node2" href="$d9/d6c/classdjango_1_1views_1_1debug_1_1_exception_reporter.html#aa161f119021aab7e67c65741ad14dccd" title="django.views.debug.Exception\lReporter.format_exception" alt="" coords="256,5,452,47"/>
<area shape="rect" id="node3" href="$d9/d6c/classdjango_1_1views_1_1debug_1_1_exception_reporter.html#a356db4aa38afe036f5f4ec4a48851f35" title="django.views.debug.Exception\lReporter.get_traceback_data" alt="" coords="256,71,452,112"/>
<area shape="rect" id="node4" href="$d9/d6c/classdjango_1_1views_1_1debug_1_1_exception_reporter.html#abc64451604ad585fdbc69758fd772ea6" title="django.views.debug.Exception\lReporter.get_traceback_html" alt="" coords="500,37,696,79"/>
<area shape="rect" id="node5" href="$d9/d6c/classdjango_1_1views_1_1debug_1_1_exception_reporter.html#a4e73474bb71b41a0f90d53345930d4d1" title="django.views.debug.Exception\lReporter.get_traceback_text" alt="" coords="500,103,696,144"/>
</map>
